esp32:
  board: lolin32_lite
  framework:
    type: esp-idf
  
esphome:
  name: monitor-tw
  on_boot:
    priority: -100.0
    then:
      - logger.log: 'HTMon boot triggered'
      - switch.turn_on: LEDint
      - script.execute: consider_deep_sleep
  on_shutdown:
    priority: -100.0
    then:
      - switch.turn_off: LEDint
      - logger.log: "HTMon shutdown triggered"


# Enable logging
logger:

wifi:
  networks:
  - ssid: !secret GKssid
    password: !secret GKpassword
  - ssid: !secret BGssid
    password: !secret BGpassword
  - ssid: !secret SSssid
    password: !secret SSpassword
  ap:
    ssid: !secret FBssid
    password: !secret FBpassword

  # Enable fallback hotspot (captive portal) in case wifi connection fails
captive_portal:


ota:
  - platform: esphome

# Enable Home Assistant API
#
# Achtung: Für Offlinekalender muss der API-Reboot auf 0s gesetzt werden, da die Tonne sonst alle 15 Minuten neu startet.
#
api:
  password: ""
  reboot_timeout: 60min  # only enable this when creating an offline device; 0s=never reboot


  
time:
  - platform: homeassistant

sun:
  latitude: 51.14°
  longitude: 9.414°
  
esp32_touch:
  setup_mode: false  
  low_voltage_reference: 0.8V  # One of 0.5V, 0.6V, 0.7V, 0.8V. Default is 0.5V.
  high_voltage_reference: 2.4V    # One of 2.4V, 2.5V, 2.6V, 2.7V. Default is 2.7V.
  voltage_attenuation: 0V    # One of 1.5V, 1V, 0.5V, 0V. Default is 0V.
  
one_wire:
  - platform: gpio
#    pin: GPIO27
    pin: GPIO26

output:
  - platform: gpio
    pin: GPIO22
    id: 'GPLEDint'

switch:
  - platform: output
    id: "LEDint"
    name: "LEDint"
    output: "GPLEDint"
    inverted: true
    restore_mode: ALWAYS_ON
  
text_sensor:
  - platform: version
    name: "ESPHome Version"

binary_sensor:
  - platform: esp32_touch
    name: "esp32touchpad"
    id: "esp32touchpad"
    pin: GPIO14
    threshold: 2000

  - platform: homeassistant
    id: prevent_deep_sleep
    name: Prevent Deep Sleep
    disabled_by_default: false
    entity_id: input_boolean.gk_heizung_prevent_deepsleep
    on_state: 
      - script.execute: consider_deep_sleep
    
sensor:  # Bedingt durch den Deep-sleep werden die Messungen nicht wirklich alle 30sek ausgeführt.
  - platform: dallas_temp
#    address: 0x7d592f7f0e64ff28 brauchen wir nicht mehr. gibt ja jetzt index :-)
    index: 0
    name: temp1
    update_interval: 30s
  - platform: dallas_temp
    index: 1
    name: temp2
    update_interval: 30s
  - platform: dallas_temp
    index: 2
    name: temp3
    update_interval: 30s
  - platform: dallas_temp
    index: 3
    name: temp4
    update_interval: 30s
  - platform: template
    name: "Raw touch value"
    device_class: "frequency"
    unit_of_measurement: "kHz"
    lambda: |-
        return id(esp32touchpad).get_value();
    update_interval: 30s
    
script:
  - id: consider_deep_sleep
    mode: restart
    then:
      - if:
          condition:
            api.connected:
          then:
            - if:
                condition:
                  binary_sensor.is_off: prevent_deep_sleep
                then:
                  - logger.log: 'Allowing sleep, per prevent_deep_sleep'
                  - deep_sleep.allow: deep_sleep_1
                else:
                  - logger.log: 'Skipping sleep, per prevent_deep_sleep'
                  - deep_sleep.prevent: deep_sleep_1
          else:  
            - logger.log: 'Skipping sleep, per no api connection'
            - deep_sleep.prevent: deep_sleep_1
            
interval:
  - interval: 10s
    then:
      - script.execute: consider_deep_sleep

deep_sleep:
  run_duration: 70sec
  sleep_duration: 5min
  id: deep_sleep_1
  wakeup_pin: 
    number: GPIO04
    mode:
      input: true
      pulldown: true
  wakeup_pin_mode: KEEP_AWAKE
  
            