esp32:
  board: lolin32_lite
  framework:
    type: esp-idf
  
esphome:
  name: monitor-tw

# Enable logging
logger:

wifi:
  ssid: !secret GKssid
#  for captive-portal remove password
  password: !secret GKpassword
  ap:
    ssid: !secret FBssid
    password: !secret FBpassword

  # Enable fallback hotspot (captive portal) in case wifi connection fails
captive_portal:


ota:
  - platform: esphome

# Enable Home Assistant API
#
# Achtung: Für Offlinekalender muss der API-Reboot auf 0s gesetzt werden, da die Tonne sonst alle 15 Minuten neu startet.
#
api:
  password: ""
 #  reboot_timeout: 0s  # only enable this when creating an offline Wastebin



  
time:
  - platform: homeassistant

sun:
  latitude: 51.14°
  longitude: 9.414°
  
# Example configuration entry
esp32_touch:
  setup_mode: false  
  
# Example configuration entry
one_wire:
  - platform: gpio
    pin: GPIO27
  
# Example configuration entry
binary_sensor:
  - platform: esp32_touch
    name: "esp32touchpad"
    id: "esp32touchpad"
    pin: GPIO33
    threshold: 100
    
    
sensor:
  - platform: dallas_temp
    address: 0x3cb3637f0e64ff28
    name: temp1
    update_interval: 300s
  - platform: dallas_temp
    address: 0x7d592f7f0e64ff28
    name: temp2
    update_interval: 300s
  - platform: template
    name: "Raw touch value"
    lambda: |-
        return id(esp32touchpad).get_value();
    update_interval: 300s