esp32:
  board: lolin32_lite
  framework:
    type: esp-idf
  
esphome:
  name: test-ds

# Enable logging
logger:

wifi:
  networks:
  - ssid: !secret GKssid
    password: !secret GKpassword
  - ssid: !secret BGssid
    password: !secret BGpassword
  - ssid: !secret SSssid
    password: !secret SSpassword
  ap:
    ssid: !secret FBssid
    password: !secret FBpassword

  # Enable fallback hotspot (captive portal) in case wifi connection fails
captive_portal:


ota:
  - platform: esphome

# Enable Home Assistant API
#
# Achtung: Für Offlinekalender muss der API-Reboot auf 0s gesetzt werden, da die Tonne sonst alle 15 Minuten neu startet.
#
api:
  password: ""
  reboot_timeout: 60min  # only enable this when creating an offline device; 0s=never reboot


  
time:
  - platform: homeassistant

sun:
  latitude: 51.14°
  longitude: 9.414°
  
esp32_touch:
  setup_mode: true  
  
one_wire:
  - platform: gpio
#    pin: GPIO27
    pin: GPIO26
  
text_sensor:
  - platform: version
    name: "ESPHome Version"

binary_sensor:
  - platform: esp32_touch
    name: "esp32touchpad"
    id: "esp32touchpad"
#    pin: GPIO33
    pin: GPIO14
    threshold: 1000
    
sensor:
  - platform: dallas_temp
    index: 0
    name: temp1
    update_interval: 5s
  - platform: dallas_temp
    index: 1
    name: temp2
    update_interval: 5s
  - platform: dallas_temp
    index: 2
    name: temp3
    update_interval: 5s
  - platform: template
    name: "Raw touch value"
    device_class: "frequency"
    unit_of_measurement: "kHz"
    lambda: |-
        return id(esp32touchpad).get_value();
    update_interval: 5s